title: Sibelclan
theme: sibelclan
#baseURL: https://www.sibelclan.com
baseURL: https://sibelclan.github.io
languageCode: es-es
defaultContentLanguage: es
languages:
  es:
    weight: 1
  en:
    weight: 2
metaDataFormat: yaml
params:
  external_links:
    store_music_url: https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley
    store_merchan_url: https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley
